server:
  port: 5859
spring:
  datasource:
    url: jdbc:mysql://101.201.149.120:3306/person_record?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ccdnf123123

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.github.chengcheng.record: debug